// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: gamestate.proto

#ifndef PROTOBUF_gamestate_2eproto__INCLUDED
#define PROTOBUF_gamestate_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 3003000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 3003000 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_table_driven.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)
namespace pmidgserialized {
class Component;
class ComponentDefaultTypeInternal;
extern ComponentDefaultTypeInternal _Component_default_instance_;
class ComponentValueBool;
class ComponentValueBoolDefaultTypeInternal;
extern ComponentValueBoolDefaultTypeInternal _ComponentValueBool_default_instance_;
class ComponentValueFloat;
class ComponentValueFloatDefaultTypeInternal;
extern ComponentValueFloatDefaultTypeInternal _ComponentValueFloat_default_instance_;
class ComponentValueString;
class ComponentValueStringDefaultTypeInternal;
extern ComponentValueStringDefaultTypeInternal _ComponentValueString_default_instance_;
class Entity;
class EntityDefaultTypeInternal;
extern EntityDefaultTypeInternal _Entity_default_instance_;
class GameState;
class GameStateDefaultTypeInternal;
extern GameStateDefaultTypeInternal _GameState_default_instance_;
class Instance;
class InstanceDefaultTypeInternal;
extern InstanceDefaultTypeInternal _Instance_default_instance_;
class System;
class SystemDefaultTypeInternal;
extern SystemDefaultTypeInternal _System_default_instance_;
}  // namespace pmidgserialized

namespace pmidgserialized {

namespace protobuf_gamestate_2eproto {
// Internal implementation detail -- do not call these.
struct TableStruct {
  static const ::google::protobuf::internal::ParseTableField entries[];
  static const ::google::protobuf::internal::AuxillaryParseTableField aux[];
  static const ::google::protobuf::internal::ParseTable schema[];
  static const ::google::protobuf::uint32 offsets[];
  static void InitDefaultsImpl();
  static void Shutdown();
};
void AddDescriptors();
void InitDefaults();
}  // namespace protobuf_gamestate_2eproto

// ===================================================================

class GameState : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:pmidgserialized.GameState) */ {
 public:
  GameState();
  virtual ~GameState();

  GameState(const GameState& from);

  inline GameState& operator=(const GameState& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields();
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields();
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const GameState& default_instance();

  static inline const GameState* internal_default_instance() {
    return reinterpret_cast<const GameState*>(
               &_GameState_default_instance_);
  }
  static PROTOBUF_CONSTEXPR int const kIndexInFileMessages =
    0;

  void Swap(GameState* other);

  // implements Message ----------------------------------------------

  inline GameState* New() const PROTOBUF_FINAL { return New(NULL); }

  GameState* New(::google::protobuf::Arena* arena) const PROTOBUF_FINAL;
  void CopyFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void MergeFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void CopyFrom(const GameState& from);
  void MergeFrom(const GameState& from);
  void Clear() PROTOBUF_FINAL;
  bool IsInitialized() const PROTOBUF_FINAL;

  size_t ByteSizeLong() const PROTOBUF_FINAL;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) PROTOBUF_FINAL;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const PROTOBUF_FINAL;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const PROTOBUF_FINAL;
  int GetCachedSize() const PROTOBUF_FINAL { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const PROTOBUF_FINAL;
  void InternalSwap(GameState* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const PROTOBUF_FINAL;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // repeated .pmidgserialized.Entity entities = 1;
  int entities_size() const;
  void clear_entities();
  static const int kEntitiesFieldNumber = 1;
  const ::pmidgserialized::Entity& entities(int index) const;
  ::pmidgserialized::Entity* mutable_entities(int index);
  ::pmidgserialized::Entity* add_entities();
  ::google::protobuf::RepeatedPtrField< ::pmidgserialized::Entity >*
      mutable_entities();
  const ::google::protobuf::RepeatedPtrField< ::pmidgserialized::Entity >&
      entities() const;

  // repeated .pmidgserialized.System active_systems = 2;
  int active_systems_size() const;
  void clear_active_systems();
  static const int kActiveSystemsFieldNumber = 2;
  const ::pmidgserialized::System& active_systems(int index) const;
  ::pmidgserialized::System* mutable_active_systems(int index);
  ::pmidgserialized::System* add_active_systems();
  ::google::protobuf::RepeatedPtrField< ::pmidgserialized::System >*
      mutable_active_systems();
  const ::google::protobuf::RepeatedPtrField< ::pmidgserialized::System >&
      active_systems() const;

  // required .pmidgserialized.Instance instance = 3;
  bool has_instance() const;
  void clear_instance();
  static const int kInstanceFieldNumber = 3;
  const ::pmidgserialized::Instance& instance() const;
  ::pmidgserialized::Instance* mutable_instance();
  ::pmidgserialized::Instance* release_instance();
  void set_allocated_instance(::pmidgserialized::Instance* instance);

  // @@protoc_insertion_point(class_scope:pmidgserialized.GameState)
 private:
  void set_has_instance();
  void clear_has_instance();

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::internal::HasBits<1> _has_bits_;
  mutable int _cached_size_;
  ::google::protobuf::RepeatedPtrField< ::pmidgserialized::Entity > entities_;
  ::google::protobuf::RepeatedPtrField< ::pmidgserialized::System > active_systems_;
  ::pmidgserialized::Instance* instance_;
  friend struct protobuf_gamestate_2eproto::TableStruct;
};
// -------------------------------------------------------------------

class Entity : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:pmidgserialized.Entity) */ {
 public:
  Entity();
  virtual ~Entity();

  Entity(const Entity& from);

  inline Entity& operator=(const Entity& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields();
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields();
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const Entity& default_instance();

  static inline const Entity* internal_default_instance() {
    return reinterpret_cast<const Entity*>(
               &_Entity_default_instance_);
  }
  static PROTOBUF_CONSTEXPR int const kIndexInFileMessages =
    1;

  void Swap(Entity* other);

  // implements Message ----------------------------------------------

  inline Entity* New() const PROTOBUF_FINAL { return New(NULL); }

  Entity* New(::google::protobuf::Arena* arena) const PROTOBUF_FINAL;
  void CopyFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void MergeFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void CopyFrom(const Entity& from);
  void MergeFrom(const Entity& from);
  void Clear() PROTOBUF_FINAL;
  bool IsInitialized() const PROTOBUF_FINAL;

  size_t ByteSizeLong() const PROTOBUF_FINAL;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) PROTOBUF_FINAL;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const PROTOBUF_FINAL;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const PROTOBUF_FINAL;
  int GetCachedSize() const PROTOBUF_FINAL { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const PROTOBUF_FINAL;
  void InternalSwap(Entity* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const PROTOBUF_FINAL;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // repeated .pmidgserialized.Component components = 2;
  int components_size() const;
  void clear_components();
  static const int kComponentsFieldNumber = 2;
  const ::pmidgserialized::Component& components(int index) const;
  ::pmidgserialized::Component* mutable_components(int index);
  ::pmidgserialized::Component* add_components();
  ::google::protobuf::RepeatedPtrField< ::pmidgserialized::Component >*
      mutable_components();
  const ::google::protobuf::RepeatedPtrField< ::pmidgserialized::Component >&
      components() const;

  // required int32 id = 1;
  bool has_id() const;
  void clear_id();
  static const int kIdFieldNumber = 1;
  ::google::protobuf::int32 id() const;
  void set_id(::google::protobuf::int32 value);

  // @@protoc_insertion_point(class_scope:pmidgserialized.Entity)
 private:
  void set_has_id();
  void clear_has_id();

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::internal::HasBits<1> _has_bits_;
  mutable int _cached_size_;
  ::google::protobuf::RepeatedPtrField< ::pmidgserialized::Component > components_;
  ::google::protobuf::int32 id_;
  friend struct protobuf_gamestate_2eproto::TableStruct;
};
// -------------------------------------------------------------------

class System : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:pmidgserialized.System) */ {
 public:
  System();
  virtual ~System();

  System(const System& from);

  inline System& operator=(const System& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields();
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields();
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const System& default_instance();

  static inline const System* internal_default_instance() {
    return reinterpret_cast<const System*>(
               &_System_default_instance_);
  }
  static PROTOBUF_CONSTEXPR int const kIndexInFileMessages =
    2;

  void Swap(System* other);

  // implements Message ----------------------------------------------

  inline System* New() const PROTOBUF_FINAL { return New(NULL); }

  System* New(::google::protobuf::Arena* arena) const PROTOBUF_FINAL;
  void CopyFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void MergeFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void CopyFrom(const System& from);
  void MergeFrom(const System& from);
  void Clear() PROTOBUF_FINAL;
  bool IsInitialized() const PROTOBUF_FINAL;

  size_t ByteSizeLong() const PROTOBUF_FINAL;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) PROTOBUF_FINAL;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const PROTOBUF_FINAL;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const PROTOBUF_FINAL;
  int GetCachedSize() const PROTOBUF_FINAL { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const PROTOBUF_FINAL;
  void InternalSwap(System* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const PROTOBUF_FINAL;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // required string name = 1;
  bool has_name() const;
  void clear_name();
  static const int kNameFieldNumber = 1;
  const ::std::string& name() const;
  void set_name(const ::std::string& value);
  #if LANG_CXX11
  void set_name(::std::string&& value);
  #endif
  void set_name(const char* value);
  void set_name(const char* value, size_t size);
  ::std::string* mutable_name();
  ::std::string* release_name();
  void set_allocated_name(::std::string* name);

  // @@protoc_insertion_point(class_scope:pmidgserialized.System)
 private:
  void set_has_name();
  void clear_has_name();

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::internal::HasBits<1> _has_bits_;
  mutable int _cached_size_;
  ::google::protobuf::internal::ArenaStringPtr name_;
  friend struct protobuf_gamestate_2eproto::TableStruct;
};
// -------------------------------------------------------------------

class Instance : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:pmidgserialized.Instance) */ {
 public:
  Instance();
  virtual ~Instance();

  Instance(const Instance& from);

  inline Instance& operator=(const Instance& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields();
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields();
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const Instance& default_instance();

  static inline const Instance* internal_default_instance() {
    return reinterpret_cast<const Instance*>(
               &_Instance_default_instance_);
  }
  static PROTOBUF_CONSTEXPR int const kIndexInFileMessages =
    3;

  void Swap(Instance* other);

  // implements Message ----------------------------------------------

  inline Instance* New() const PROTOBUF_FINAL { return New(NULL); }

  Instance* New(::google::protobuf::Arena* arena) const PROTOBUF_FINAL;
  void CopyFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void MergeFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void CopyFrom(const Instance& from);
  void MergeFrom(const Instance& from);
  void Clear() PROTOBUF_FINAL;
  bool IsInitialized() const PROTOBUF_FINAL;

  size_t ByteSizeLong() const PROTOBUF_FINAL;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) PROTOBUF_FINAL;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const PROTOBUF_FINAL;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const PROTOBUF_FINAL;
  int GetCachedSize() const PROTOBUF_FINAL { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const PROTOBUF_FINAL;
  void InternalSwap(Instance* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const PROTOBUF_FINAL;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // required string tilemap = 1;
  bool has_tilemap() const;
  void clear_tilemap();
  static const int kTilemapFieldNumber = 1;
  const ::std::string& tilemap() const;
  void set_tilemap(const ::std::string& value);
  #if LANG_CXX11
  void set_tilemap(::std::string&& value);
  #endif
  void set_tilemap(const char* value);
  void set_tilemap(const char* value, size_t size);
  ::std::string* mutable_tilemap();
  ::std::string* release_tilemap();
  void set_allocated_tilemap(::std::string* tilemap);

  // @@protoc_insertion_point(class_scope:pmidgserialized.Instance)
 private:
  void set_has_tilemap();
  void clear_has_tilemap();

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::internal::HasBits<1> _has_bits_;
  mutable int _cached_size_;
  ::google::protobuf::internal::ArenaStringPtr tilemap_;
  friend struct protobuf_gamestate_2eproto::TableStruct;
};
// -------------------------------------------------------------------

class Component : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:pmidgserialized.Component) */ {
 public:
  Component();
  virtual ~Component();

  Component(const Component& from);

  inline Component& operator=(const Component& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields();
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields();
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const Component& default_instance();

  static inline const Component* internal_default_instance() {
    return reinterpret_cast<const Component*>(
               &_Component_default_instance_);
  }
  static PROTOBUF_CONSTEXPR int const kIndexInFileMessages =
    4;

  void Swap(Component* other);

  // implements Message ----------------------------------------------

  inline Component* New() const PROTOBUF_FINAL { return New(NULL); }

  Component* New(::google::protobuf::Arena* arena) const PROTOBUF_FINAL;
  void CopyFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void MergeFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void CopyFrom(const Component& from);
  void MergeFrom(const Component& from);
  void Clear() PROTOBUF_FINAL;
  bool IsInitialized() const PROTOBUF_FINAL;

  size_t ByteSizeLong() const PROTOBUF_FINAL;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) PROTOBUF_FINAL;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const PROTOBUF_FINAL;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const PROTOBUF_FINAL;
  int GetCachedSize() const PROTOBUF_FINAL { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const PROTOBUF_FINAL;
  void InternalSwap(Component* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const PROTOBUF_FINAL;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // repeated .pmidgserialized.ComponentValueString string_values = 2;
  int string_values_size() const;
  void clear_string_values();
  static const int kStringValuesFieldNumber = 2;
  const ::pmidgserialized::ComponentValueString& string_values(int index) const;
  ::pmidgserialized::ComponentValueString* mutable_string_values(int index);
  ::pmidgserialized::ComponentValueString* add_string_values();
  ::google::protobuf::RepeatedPtrField< ::pmidgserialized::ComponentValueString >*
      mutable_string_values();
  const ::google::protobuf::RepeatedPtrField< ::pmidgserialized::ComponentValueString >&
      string_values() const;

  // repeated .pmidgserialized.ComponentValueBool bool_values = 3;
  int bool_values_size() const;
  void clear_bool_values();
  static const int kBoolValuesFieldNumber = 3;
  const ::pmidgserialized::ComponentValueBool& bool_values(int index) const;
  ::pmidgserialized::ComponentValueBool* mutable_bool_values(int index);
  ::pmidgserialized::ComponentValueBool* add_bool_values();
  ::google::protobuf::RepeatedPtrField< ::pmidgserialized::ComponentValueBool >*
      mutable_bool_values();
  const ::google::protobuf::RepeatedPtrField< ::pmidgserialized::ComponentValueBool >&
      bool_values() const;

  // repeated .pmidgserialized.ComponentValueFloat float_values = 4;
  int float_values_size() const;
  void clear_float_values();
  static const int kFloatValuesFieldNumber = 4;
  const ::pmidgserialized::ComponentValueFloat& float_values(int index) const;
  ::pmidgserialized::ComponentValueFloat* mutable_float_values(int index);
  ::pmidgserialized::ComponentValueFloat* add_float_values();
  ::google::protobuf::RepeatedPtrField< ::pmidgserialized::ComponentValueFloat >*
      mutable_float_values();
  const ::google::protobuf::RepeatedPtrField< ::pmidgserialized::ComponentValueFloat >&
      float_values() const;

  // required string name = 1;
  bool has_name() const;
  void clear_name();
  static const int kNameFieldNumber = 1;
  const ::std::string& name() const;
  void set_name(const ::std::string& value);
  #if LANG_CXX11
  void set_name(::std::string&& value);
  #endif
  void set_name(const char* value);
  void set_name(const char* value, size_t size);
  ::std::string* mutable_name();
  ::std::string* release_name();
  void set_allocated_name(::std::string* name);

  // @@protoc_insertion_point(class_scope:pmidgserialized.Component)
 private:
  void set_has_name();
  void clear_has_name();

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::internal::HasBits<1> _has_bits_;
  mutable int _cached_size_;
  ::google::protobuf::RepeatedPtrField< ::pmidgserialized::ComponentValueString > string_values_;
  ::google::protobuf::RepeatedPtrField< ::pmidgserialized::ComponentValueBool > bool_values_;
  ::google::protobuf::RepeatedPtrField< ::pmidgserialized::ComponentValueFloat > float_values_;
  ::google::protobuf::internal::ArenaStringPtr name_;
  friend struct protobuf_gamestate_2eproto::TableStruct;
};
// -------------------------------------------------------------------

class ComponentValueString : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:pmidgserialized.ComponentValueString) */ {
 public:
  ComponentValueString();
  virtual ~ComponentValueString();

  ComponentValueString(const ComponentValueString& from);

  inline ComponentValueString& operator=(const ComponentValueString& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields();
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields();
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const ComponentValueString& default_instance();

  static inline const ComponentValueString* internal_default_instance() {
    return reinterpret_cast<const ComponentValueString*>(
               &_ComponentValueString_default_instance_);
  }
  static PROTOBUF_CONSTEXPR int const kIndexInFileMessages =
    5;

  void Swap(ComponentValueString* other);

  // implements Message ----------------------------------------------

  inline ComponentValueString* New() const PROTOBUF_FINAL { return New(NULL); }

  ComponentValueString* New(::google::protobuf::Arena* arena) const PROTOBUF_FINAL;
  void CopyFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void MergeFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void CopyFrom(const ComponentValueString& from);
  void MergeFrom(const ComponentValueString& from);
  void Clear() PROTOBUF_FINAL;
  bool IsInitialized() const PROTOBUF_FINAL;

  size_t ByteSizeLong() const PROTOBUF_FINAL;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) PROTOBUF_FINAL;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const PROTOBUF_FINAL;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const PROTOBUF_FINAL;
  int GetCachedSize() const PROTOBUF_FINAL { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const PROTOBUF_FINAL;
  void InternalSwap(ComponentValueString* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const PROTOBUF_FINAL;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // required string value_name = 1;
  bool has_value_name() const;
  void clear_value_name();
  static const int kValueNameFieldNumber = 1;
  const ::std::string& value_name() const;
  void set_value_name(const ::std::string& value);
  #if LANG_CXX11
  void set_value_name(::std::string&& value);
  #endif
  void set_value_name(const char* value);
  void set_value_name(const char* value, size_t size);
  ::std::string* mutable_value_name();
  ::std::string* release_value_name();
  void set_allocated_value_name(::std::string* value_name);

  // required string value = 2;
  bool has_value() const;
  void clear_value();
  static const int kValueFieldNumber = 2;
  const ::std::string& value() const;
  void set_value(const ::std::string& value);
  #if LANG_CXX11
  void set_value(::std::string&& value);
  #endif
  void set_value(const char* value);
  void set_value(const char* value, size_t size);
  ::std::string* mutable_value();
  ::std::string* release_value();
  void set_allocated_value(::std::string* value);

  // @@protoc_insertion_point(class_scope:pmidgserialized.ComponentValueString)
 private:
  void set_has_value_name();
  void clear_has_value_name();
  void set_has_value();
  void clear_has_value();

  // helper for ByteSizeLong()
  size_t RequiredFieldsByteSizeFallback() const;

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::internal::HasBits<1> _has_bits_;
  mutable int _cached_size_;
  ::google::protobuf::internal::ArenaStringPtr value_name_;
  ::google::protobuf::internal::ArenaStringPtr value_;
  friend struct protobuf_gamestate_2eproto::TableStruct;
};
// -------------------------------------------------------------------

class ComponentValueBool : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:pmidgserialized.ComponentValueBool) */ {
 public:
  ComponentValueBool();
  virtual ~ComponentValueBool();

  ComponentValueBool(const ComponentValueBool& from);

  inline ComponentValueBool& operator=(const ComponentValueBool& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields();
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields();
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const ComponentValueBool& default_instance();

  static inline const ComponentValueBool* internal_default_instance() {
    return reinterpret_cast<const ComponentValueBool*>(
               &_ComponentValueBool_default_instance_);
  }
  static PROTOBUF_CONSTEXPR int const kIndexInFileMessages =
    6;

  void Swap(ComponentValueBool* other);

  // implements Message ----------------------------------------------

  inline ComponentValueBool* New() const PROTOBUF_FINAL { return New(NULL); }

  ComponentValueBool* New(::google::protobuf::Arena* arena) const PROTOBUF_FINAL;
  void CopyFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void MergeFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void CopyFrom(const ComponentValueBool& from);
  void MergeFrom(const ComponentValueBool& from);
  void Clear() PROTOBUF_FINAL;
  bool IsInitialized() const PROTOBUF_FINAL;

  size_t ByteSizeLong() const PROTOBUF_FINAL;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) PROTOBUF_FINAL;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const PROTOBUF_FINAL;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const PROTOBUF_FINAL;
  int GetCachedSize() const PROTOBUF_FINAL { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const PROTOBUF_FINAL;
  void InternalSwap(ComponentValueBool* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const PROTOBUF_FINAL;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // required string value_name = 1;
  bool has_value_name() const;
  void clear_value_name();
  static const int kValueNameFieldNumber = 1;
  const ::std::string& value_name() const;
  void set_value_name(const ::std::string& value);
  #if LANG_CXX11
  void set_value_name(::std::string&& value);
  #endif
  void set_value_name(const char* value);
  void set_value_name(const char* value, size_t size);
  ::std::string* mutable_value_name();
  ::std::string* release_value_name();
  void set_allocated_value_name(::std::string* value_name);

  // required bool value = 2;
  bool has_value() const;
  void clear_value();
  static const int kValueFieldNumber = 2;
  bool value() const;
  void set_value(bool value);

  // @@protoc_insertion_point(class_scope:pmidgserialized.ComponentValueBool)
 private:
  void set_has_value_name();
  void clear_has_value_name();
  void set_has_value();
  void clear_has_value();

  // helper for ByteSizeLong()
  size_t RequiredFieldsByteSizeFallback() const;

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::internal::HasBits<1> _has_bits_;
  mutable int _cached_size_;
  ::google::protobuf::internal::ArenaStringPtr value_name_;
  bool value_;
  friend struct protobuf_gamestate_2eproto::TableStruct;
};
// -------------------------------------------------------------------

class ComponentValueFloat : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:pmidgserialized.ComponentValueFloat) */ {
 public:
  ComponentValueFloat();
  virtual ~ComponentValueFloat();

  ComponentValueFloat(const ComponentValueFloat& from);

  inline ComponentValueFloat& operator=(const ComponentValueFloat& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields();
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields();
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const ComponentValueFloat& default_instance();

  static inline const ComponentValueFloat* internal_default_instance() {
    return reinterpret_cast<const ComponentValueFloat*>(
               &_ComponentValueFloat_default_instance_);
  }
  static PROTOBUF_CONSTEXPR int const kIndexInFileMessages =
    7;

  void Swap(ComponentValueFloat* other);

  // implements Message ----------------------------------------------

  inline ComponentValueFloat* New() const PROTOBUF_FINAL { return New(NULL); }

  ComponentValueFloat* New(::google::protobuf::Arena* arena) const PROTOBUF_FINAL;
  void CopyFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void MergeFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void CopyFrom(const ComponentValueFloat& from);
  void MergeFrom(const ComponentValueFloat& from);
  void Clear() PROTOBUF_FINAL;
  bool IsInitialized() const PROTOBUF_FINAL;

  size_t ByteSizeLong() const PROTOBUF_FINAL;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) PROTOBUF_FINAL;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const PROTOBUF_FINAL;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const PROTOBUF_FINAL;
  int GetCachedSize() const PROTOBUF_FINAL { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const PROTOBUF_FINAL;
  void InternalSwap(ComponentValueFloat* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const PROTOBUF_FINAL;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // required string value_name = 1;
  bool has_value_name() const;
  void clear_value_name();
  static const int kValueNameFieldNumber = 1;
  const ::std::string& value_name() const;
  void set_value_name(const ::std::string& value);
  #if LANG_CXX11
  void set_value_name(::std::string&& value);
  #endif
  void set_value_name(const char* value);
  void set_value_name(const char* value, size_t size);
  ::std::string* mutable_value_name();
  ::std::string* release_value_name();
  void set_allocated_value_name(::std::string* value_name);

  // required float value = 2;
  bool has_value() const;
  void clear_value();
  static const int kValueFieldNumber = 2;
  float value() const;
  void set_value(float value);

  // @@protoc_insertion_point(class_scope:pmidgserialized.ComponentValueFloat)
 private:
  void set_has_value_name();
  void clear_has_value_name();
  void set_has_value();
  void clear_has_value();

  // helper for ByteSizeLong()
  size_t RequiredFieldsByteSizeFallback() const;

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::internal::HasBits<1> _has_bits_;
  mutable int _cached_size_;
  ::google::protobuf::internal::ArenaStringPtr value_name_;
  float value_;
  friend struct protobuf_gamestate_2eproto::TableStruct;
};
// ===================================================================


// ===================================================================

#if !PROTOBUF_INLINE_NOT_IN_HEADERS
// GameState

// repeated .pmidgserialized.Entity entities = 1;
inline int GameState::entities_size() const {
  return entities_.size();
}
inline void GameState::clear_entities() {
  entities_.Clear();
}
inline const ::pmidgserialized::Entity& GameState::entities(int index) const {
  // @@protoc_insertion_point(field_get:pmidgserialized.GameState.entities)
  return entities_.Get(index);
}
inline ::pmidgserialized::Entity* GameState::mutable_entities(int index) {
  // @@protoc_insertion_point(field_mutable:pmidgserialized.GameState.entities)
  return entities_.Mutable(index);
}
inline ::pmidgserialized::Entity* GameState::add_entities() {
  // @@protoc_insertion_point(field_add:pmidgserialized.GameState.entities)
  return entities_.Add();
}
inline ::google::protobuf::RepeatedPtrField< ::pmidgserialized::Entity >*
GameState::mutable_entities() {
  // @@protoc_insertion_point(field_mutable_list:pmidgserialized.GameState.entities)
  return &entities_;
}
inline const ::google::protobuf::RepeatedPtrField< ::pmidgserialized::Entity >&
GameState::entities() const {
  // @@protoc_insertion_point(field_list:pmidgserialized.GameState.entities)
  return entities_;
}

// repeated .pmidgserialized.System active_systems = 2;
inline int GameState::active_systems_size() const {
  return active_systems_.size();
}
inline void GameState::clear_active_systems() {
  active_systems_.Clear();
}
inline const ::pmidgserialized::System& GameState::active_systems(int index) const {
  // @@protoc_insertion_point(field_get:pmidgserialized.GameState.active_systems)
  return active_systems_.Get(index);
}
inline ::pmidgserialized::System* GameState::mutable_active_systems(int index) {
  // @@protoc_insertion_point(field_mutable:pmidgserialized.GameState.active_systems)
  return active_systems_.Mutable(index);
}
inline ::pmidgserialized::System* GameState::add_active_systems() {
  // @@protoc_insertion_point(field_add:pmidgserialized.GameState.active_systems)
  return active_systems_.Add();
}
inline ::google::protobuf::RepeatedPtrField< ::pmidgserialized::System >*
GameState::mutable_active_systems() {
  // @@protoc_insertion_point(field_mutable_list:pmidgserialized.GameState.active_systems)
  return &active_systems_;
}
inline const ::google::protobuf::RepeatedPtrField< ::pmidgserialized::System >&
GameState::active_systems() const {
  // @@protoc_insertion_point(field_list:pmidgserialized.GameState.active_systems)
  return active_systems_;
}

// required .pmidgserialized.Instance instance = 3;
inline bool GameState::has_instance() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void GameState::set_has_instance() {
  _has_bits_[0] |= 0x00000001u;
}
inline void GameState::clear_has_instance() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void GameState::clear_instance() {
  if (instance_ != NULL) instance_->::pmidgserialized::Instance::Clear();
  clear_has_instance();
}
inline const ::pmidgserialized::Instance& GameState::instance() const {
  // @@protoc_insertion_point(field_get:pmidgserialized.GameState.instance)
  return instance_ != NULL ? *instance_
                         : *::pmidgserialized::Instance::internal_default_instance();
}
inline ::pmidgserialized::Instance* GameState::mutable_instance() {
  set_has_instance();
  if (instance_ == NULL) {
    instance_ = new ::pmidgserialized::Instance;
  }
  // @@protoc_insertion_point(field_mutable:pmidgserialized.GameState.instance)
  return instance_;
}
inline ::pmidgserialized::Instance* GameState::release_instance() {
  // @@protoc_insertion_point(field_release:pmidgserialized.GameState.instance)
  clear_has_instance();
  ::pmidgserialized::Instance* temp = instance_;
  instance_ = NULL;
  return temp;
}
inline void GameState::set_allocated_instance(::pmidgserialized::Instance* instance) {
  delete instance_;
  instance_ = instance;
  if (instance) {
    set_has_instance();
  } else {
    clear_has_instance();
  }
  // @@protoc_insertion_point(field_set_allocated:pmidgserialized.GameState.instance)
}

// -------------------------------------------------------------------

// Entity

// required int32 id = 1;
inline bool Entity::has_id() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void Entity::set_has_id() {
  _has_bits_[0] |= 0x00000001u;
}
inline void Entity::clear_has_id() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void Entity::clear_id() {
  id_ = 0;
  clear_has_id();
}
inline ::google::protobuf::int32 Entity::id() const {
  // @@protoc_insertion_point(field_get:pmidgserialized.Entity.id)
  return id_;
}
inline void Entity::set_id(::google::protobuf::int32 value) {
  set_has_id();
  id_ = value;
  // @@protoc_insertion_point(field_set:pmidgserialized.Entity.id)
}

// repeated .pmidgserialized.Component components = 2;
inline int Entity::components_size() const {
  return components_.size();
}
inline void Entity::clear_components() {
  components_.Clear();
}
inline const ::pmidgserialized::Component& Entity::components(int index) const {
  // @@protoc_insertion_point(field_get:pmidgserialized.Entity.components)
  return components_.Get(index);
}
inline ::pmidgserialized::Component* Entity::mutable_components(int index) {
  // @@protoc_insertion_point(field_mutable:pmidgserialized.Entity.components)
  return components_.Mutable(index);
}
inline ::pmidgserialized::Component* Entity::add_components() {
  // @@protoc_insertion_point(field_add:pmidgserialized.Entity.components)
  return components_.Add();
}
inline ::google::protobuf::RepeatedPtrField< ::pmidgserialized::Component >*
Entity::mutable_components() {
  // @@protoc_insertion_point(field_mutable_list:pmidgserialized.Entity.components)
  return &components_;
}
inline const ::google::protobuf::RepeatedPtrField< ::pmidgserialized::Component >&
Entity::components() const {
  // @@protoc_insertion_point(field_list:pmidgserialized.Entity.components)
  return components_;
}

// -------------------------------------------------------------------

// System

// required string name = 1;
inline bool System::has_name() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void System::set_has_name() {
  _has_bits_[0] |= 0x00000001u;
}
inline void System::clear_has_name() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void System::clear_name() {
  name_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  clear_has_name();
}
inline const ::std::string& System::name() const {
  // @@protoc_insertion_point(field_get:pmidgserialized.System.name)
  return name_.GetNoArena();
}
inline void System::set_name(const ::std::string& value) {
  set_has_name();
  name_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:pmidgserialized.System.name)
}
#if LANG_CXX11
inline void System::set_name(::std::string&& value) {
  set_has_name();
  name_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:pmidgserialized.System.name)
}
#endif
inline void System::set_name(const char* value) {
  GOOGLE_DCHECK(value != NULL);
  set_has_name();
  name_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:pmidgserialized.System.name)
}
inline void System::set_name(const char* value, size_t size) {
  set_has_name();
  name_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:pmidgserialized.System.name)
}
inline ::std::string* System::mutable_name() {
  set_has_name();
  // @@protoc_insertion_point(field_mutable:pmidgserialized.System.name)
  return name_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* System::release_name() {
  // @@protoc_insertion_point(field_release:pmidgserialized.System.name)
  clear_has_name();
  return name_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void System::set_allocated_name(::std::string* name) {
  if (name != NULL) {
    set_has_name();
  } else {
    clear_has_name();
  }
  name_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), name);
  // @@protoc_insertion_point(field_set_allocated:pmidgserialized.System.name)
}

// -------------------------------------------------------------------

// Instance

// required string tilemap = 1;
inline bool Instance::has_tilemap() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void Instance::set_has_tilemap() {
  _has_bits_[0] |= 0x00000001u;
}
inline void Instance::clear_has_tilemap() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void Instance::clear_tilemap() {
  tilemap_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  clear_has_tilemap();
}
inline const ::std::string& Instance::tilemap() const {
  // @@protoc_insertion_point(field_get:pmidgserialized.Instance.tilemap)
  return tilemap_.GetNoArena();
}
inline void Instance::set_tilemap(const ::std::string& value) {
  set_has_tilemap();
  tilemap_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:pmidgserialized.Instance.tilemap)
}
#if LANG_CXX11
inline void Instance::set_tilemap(::std::string&& value) {
  set_has_tilemap();
  tilemap_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:pmidgserialized.Instance.tilemap)
}
#endif
inline void Instance::set_tilemap(const char* value) {
  GOOGLE_DCHECK(value != NULL);
  set_has_tilemap();
  tilemap_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:pmidgserialized.Instance.tilemap)
}
inline void Instance::set_tilemap(const char* value, size_t size) {
  set_has_tilemap();
  tilemap_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:pmidgserialized.Instance.tilemap)
}
inline ::std::string* Instance::mutable_tilemap() {
  set_has_tilemap();
  // @@protoc_insertion_point(field_mutable:pmidgserialized.Instance.tilemap)
  return tilemap_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* Instance::release_tilemap() {
  // @@protoc_insertion_point(field_release:pmidgserialized.Instance.tilemap)
  clear_has_tilemap();
  return tilemap_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void Instance::set_allocated_tilemap(::std::string* tilemap) {
  if (tilemap != NULL) {
    set_has_tilemap();
  } else {
    clear_has_tilemap();
  }
  tilemap_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), tilemap);
  // @@protoc_insertion_point(field_set_allocated:pmidgserialized.Instance.tilemap)
}

// -------------------------------------------------------------------

// Component

// required string name = 1;
inline bool Component::has_name() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void Component::set_has_name() {
  _has_bits_[0] |= 0x00000001u;
}
inline void Component::clear_has_name() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void Component::clear_name() {
  name_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  clear_has_name();
}
inline const ::std::string& Component::name() const {
  // @@protoc_insertion_point(field_get:pmidgserialized.Component.name)
  return name_.GetNoArena();
}
inline void Component::set_name(const ::std::string& value) {
  set_has_name();
  name_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:pmidgserialized.Component.name)
}
#if LANG_CXX11
inline void Component::set_name(::std::string&& value) {
  set_has_name();
  name_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:pmidgserialized.Component.name)
}
#endif
inline void Component::set_name(const char* value) {
  GOOGLE_DCHECK(value != NULL);
  set_has_name();
  name_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:pmidgserialized.Component.name)
}
inline void Component::set_name(const char* value, size_t size) {
  set_has_name();
  name_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:pmidgserialized.Component.name)
}
inline ::std::string* Component::mutable_name() {
  set_has_name();
  // @@protoc_insertion_point(field_mutable:pmidgserialized.Component.name)
  return name_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* Component::release_name() {
  // @@protoc_insertion_point(field_release:pmidgserialized.Component.name)
  clear_has_name();
  return name_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void Component::set_allocated_name(::std::string* name) {
  if (name != NULL) {
    set_has_name();
  } else {
    clear_has_name();
  }
  name_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), name);
  // @@protoc_insertion_point(field_set_allocated:pmidgserialized.Component.name)
}

// repeated .pmidgserialized.ComponentValueString string_values = 2;
inline int Component::string_values_size() const {
  return string_values_.size();
}
inline void Component::clear_string_values() {
  string_values_.Clear();
}
inline const ::pmidgserialized::ComponentValueString& Component::string_values(int index) const {
  // @@protoc_insertion_point(field_get:pmidgserialized.Component.string_values)
  return string_values_.Get(index);
}
inline ::pmidgserialized::ComponentValueString* Component::mutable_string_values(int index) {
  // @@protoc_insertion_point(field_mutable:pmidgserialized.Component.string_values)
  return string_values_.Mutable(index);
}
inline ::pmidgserialized::ComponentValueString* Component::add_string_values() {
  // @@protoc_insertion_point(field_add:pmidgserialized.Component.string_values)
  return string_values_.Add();
}
inline ::google::protobuf::RepeatedPtrField< ::pmidgserialized::ComponentValueString >*
Component::mutable_string_values() {
  // @@protoc_insertion_point(field_mutable_list:pmidgserialized.Component.string_values)
  return &string_values_;
}
inline const ::google::protobuf::RepeatedPtrField< ::pmidgserialized::ComponentValueString >&
Component::string_values() const {
  // @@protoc_insertion_point(field_list:pmidgserialized.Component.string_values)
  return string_values_;
}

// repeated .pmidgserialized.ComponentValueBool bool_values = 3;
inline int Component::bool_values_size() const {
  return bool_values_.size();
}
inline void Component::clear_bool_values() {
  bool_values_.Clear();
}
inline const ::pmidgserialized::ComponentValueBool& Component::bool_values(int index) const {
  // @@protoc_insertion_point(field_get:pmidgserialized.Component.bool_values)
  return bool_values_.Get(index);
}
inline ::pmidgserialized::ComponentValueBool* Component::mutable_bool_values(int index) {
  // @@protoc_insertion_point(field_mutable:pmidgserialized.Component.bool_values)
  return bool_values_.Mutable(index);
}
inline ::pmidgserialized::ComponentValueBool* Component::add_bool_values() {
  // @@protoc_insertion_point(field_add:pmidgserialized.Component.bool_values)
  return bool_values_.Add();
}
inline ::google::protobuf::RepeatedPtrField< ::pmidgserialized::ComponentValueBool >*
Component::mutable_bool_values() {
  // @@protoc_insertion_point(field_mutable_list:pmidgserialized.Component.bool_values)
  return &bool_values_;
}
inline const ::google::protobuf::RepeatedPtrField< ::pmidgserialized::ComponentValueBool >&
Component::bool_values() const {
  // @@protoc_insertion_point(field_list:pmidgserialized.Component.bool_values)
  return bool_values_;
}

// repeated .pmidgserialized.ComponentValueFloat float_values = 4;
inline int Component::float_values_size() const {
  return float_values_.size();
}
inline void Component::clear_float_values() {
  float_values_.Clear();
}
inline const ::pmidgserialized::ComponentValueFloat& Component::float_values(int index) const {
  // @@protoc_insertion_point(field_get:pmidgserialized.Component.float_values)
  return float_values_.Get(index);
}
inline ::pmidgserialized::ComponentValueFloat* Component::mutable_float_values(int index) {
  // @@protoc_insertion_point(field_mutable:pmidgserialized.Component.float_values)
  return float_values_.Mutable(index);
}
inline ::pmidgserialized::ComponentValueFloat* Component::add_float_values() {
  // @@protoc_insertion_point(field_add:pmidgserialized.Component.float_values)
  return float_values_.Add();
}
inline ::google::protobuf::RepeatedPtrField< ::pmidgserialized::ComponentValueFloat >*
Component::mutable_float_values() {
  // @@protoc_insertion_point(field_mutable_list:pmidgserialized.Component.float_values)
  return &float_values_;
}
inline const ::google::protobuf::RepeatedPtrField< ::pmidgserialized::ComponentValueFloat >&
Component::float_values() const {
  // @@protoc_insertion_point(field_list:pmidgserialized.Component.float_values)
  return float_values_;
}

// -------------------------------------------------------------------

// ComponentValueString

// required string value_name = 1;
inline bool ComponentValueString::has_value_name() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void ComponentValueString::set_has_value_name() {
  _has_bits_[0] |= 0x00000001u;
}
inline void ComponentValueString::clear_has_value_name() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void ComponentValueString::clear_value_name() {
  value_name_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  clear_has_value_name();
}
inline const ::std::string& ComponentValueString::value_name() const {
  // @@protoc_insertion_point(field_get:pmidgserialized.ComponentValueString.value_name)
  return value_name_.GetNoArena();
}
inline void ComponentValueString::set_value_name(const ::std::string& value) {
  set_has_value_name();
  value_name_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:pmidgserialized.ComponentValueString.value_name)
}
#if LANG_CXX11
inline void ComponentValueString::set_value_name(::std::string&& value) {
  set_has_value_name();
  value_name_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:pmidgserialized.ComponentValueString.value_name)
}
#endif
inline void ComponentValueString::set_value_name(const char* value) {
  GOOGLE_DCHECK(value != NULL);
  set_has_value_name();
  value_name_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:pmidgserialized.ComponentValueString.value_name)
}
inline void ComponentValueString::set_value_name(const char* value, size_t size) {
  set_has_value_name();
  value_name_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:pmidgserialized.ComponentValueString.value_name)
}
inline ::std::string* ComponentValueString::mutable_value_name() {
  set_has_value_name();
  // @@protoc_insertion_point(field_mutable:pmidgserialized.ComponentValueString.value_name)
  return value_name_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* ComponentValueString::release_value_name() {
  // @@protoc_insertion_point(field_release:pmidgserialized.ComponentValueString.value_name)
  clear_has_value_name();
  return value_name_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void ComponentValueString::set_allocated_value_name(::std::string* value_name) {
  if (value_name != NULL) {
    set_has_value_name();
  } else {
    clear_has_value_name();
  }
  value_name_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value_name);
  // @@protoc_insertion_point(field_set_allocated:pmidgserialized.ComponentValueString.value_name)
}

// required string value = 2;
inline bool ComponentValueString::has_value() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void ComponentValueString::set_has_value() {
  _has_bits_[0] |= 0x00000002u;
}
inline void ComponentValueString::clear_has_value() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void ComponentValueString::clear_value() {
  value_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  clear_has_value();
}
inline const ::std::string& ComponentValueString::value() const {
  // @@protoc_insertion_point(field_get:pmidgserialized.ComponentValueString.value)
  return value_.GetNoArena();
}
inline void ComponentValueString::set_value(const ::std::string& value) {
  set_has_value();
  value_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:pmidgserialized.ComponentValueString.value)
}
#if LANG_CXX11
inline void ComponentValueString::set_value(::std::string&& value) {
  set_has_value();
  value_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:pmidgserialized.ComponentValueString.value)
}
#endif
inline void ComponentValueString::set_value(const char* value) {
  GOOGLE_DCHECK(value != NULL);
  set_has_value();
  value_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:pmidgserialized.ComponentValueString.value)
}
inline void ComponentValueString::set_value(const char* value, size_t size) {
  set_has_value();
  value_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:pmidgserialized.ComponentValueString.value)
}
inline ::std::string* ComponentValueString::mutable_value() {
  set_has_value();
  // @@protoc_insertion_point(field_mutable:pmidgserialized.ComponentValueString.value)
  return value_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* ComponentValueString::release_value() {
  // @@protoc_insertion_point(field_release:pmidgserialized.ComponentValueString.value)
  clear_has_value();
  return value_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void ComponentValueString::set_allocated_value(::std::string* value) {
  if (value != NULL) {
    set_has_value();
  } else {
    clear_has_value();
  }
  value_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set_allocated:pmidgserialized.ComponentValueString.value)
}

// -------------------------------------------------------------------

// ComponentValueBool

// required string value_name = 1;
inline bool ComponentValueBool::has_value_name() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void ComponentValueBool::set_has_value_name() {
  _has_bits_[0] |= 0x00000001u;
}
inline void ComponentValueBool::clear_has_value_name() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void ComponentValueBool::clear_value_name() {
  value_name_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  clear_has_value_name();
}
inline const ::std::string& ComponentValueBool::value_name() const {
  // @@protoc_insertion_point(field_get:pmidgserialized.ComponentValueBool.value_name)
  return value_name_.GetNoArena();
}
inline void ComponentValueBool::set_value_name(const ::std::string& value) {
  set_has_value_name();
  value_name_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:pmidgserialized.ComponentValueBool.value_name)
}
#if LANG_CXX11
inline void ComponentValueBool::set_value_name(::std::string&& value) {
  set_has_value_name();
  value_name_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:pmidgserialized.ComponentValueBool.value_name)
}
#endif
inline void ComponentValueBool::set_value_name(const char* value) {
  GOOGLE_DCHECK(value != NULL);
  set_has_value_name();
  value_name_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:pmidgserialized.ComponentValueBool.value_name)
}
inline void ComponentValueBool::set_value_name(const char* value, size_t size) {
  set_has_value_name();
  value_name_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:pmidgserialized.ComponentValueBool.value_name)
}
inline ::std::string* ComponentValueBool::mutable_value_name() {
  set_has_value_name();
  // @@protoc_insertion_point(field_mutable:pmidgserialized.ComponentValueBool.value_name)
  return value_name_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* ComponentValueBool::release_value_name() {
  // @@protoc_insertion_point(field_release:pmidgserialized.ComponentValueBool.value_name)
  clear_has_value_name();
  return value_name_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void ComponentValueBool::set_allocated_value_name(::std::string* value_name) {
  if (value_name != NULL) {
    set_has_value_name();
  } else {
    clear_has_value_name();
  }
  value_name_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value_name);
  // @@protoc_insertion_point(field_set_allocated:pmidgserialized.ComponentValueBool.value_name)
}

// required bool value = 2;
inline bool ComponentValueBool::has_value() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void ComponentValueBool::set_has_value() {
  _has_bits_[0] |= 0x00000002u;
}
inline void ComponentValueBool::clear_has_value() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void ComponentValueBool::clear_value() {
  value_ = false;
  clear_has_value();
}
inline bool ComponentValueBool::value() const {
  // @@protoc_insertion_point(field_get:pmidgserialized.ComponentValueBool.value)
  return value_;
}
inline void ComponentValueBool::set_value(bool value) {
  set_has_value();
  value_ = value;
  // @@protoc_insertion_point(field_set:pmidgserialized.ComponentValueBool.value)
}

// -------------------------------------------------------------------

// ComponentValueFloat

// required string value_name = 1;
inline bool ComponentValueFloat::has_value_name() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void ComponentValueFloat::set_has_value_name() {
  _has_bits_[0] |= 0x00000001u;
}
inline void ComponentValueFloat::clear_has_value_name() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void ComponentValueFloat::clear_value_name() {
  value_name_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  clear_has_value_name();
}
inline const ::std::string& ComponentValueFloat::value_name() const {
  // @@protoc_insertion_point(field_get:pmidgserialized.ComponentValueFloat.value_name)
  return value_name_.GetNoArena();
}
inline void ComponentValueFloat::set_value_name(const ::std::string& value) {
  set_has_value_name();
  value_name_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:pmidgserialized.ComponentValueFloat.value_name)
}
#if LANG_CXX11
inline void ComponentValueFloat::set_value_name(::std::string&& value) {
  set_has_value_name();
  value_name_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:pmidgserialized.ComponentValueFloat.value_name)
}
#endif
inline void ComponentValueFloat::set_value_name(const char* value) {
  GOOGLE_DCHECK(value != NULL);
  set_has_value_name();
  value_name_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:pmidgserialized.ComponentValueFloat.value_name)
}
inline void ComponentValueFloat::set_value_name(const char* value, size_t size) {
  set_has_value_name();
  value_name_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:pmidgserialized.ComponentValueFloat.value_name)
}
inline ::std::string* ComponentValueFloat::mutable_value_name() {
  set_has_value_name();
  // @@protoc_insertion_point(field_mutable:pmidgserialized.ComponentValueFloat.value_name)
  return value_name_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* ComponentValueFloat::release_value_name() {
  // @@protoc_insertion_point(field_release:pmidgserialized.ComponentValueFloat.value_name)
  clear_has_value_name();
  return value_name_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void ComponentValueFloat::set_allocated_value_name(::std::string* value_name) {
  if (value_name != NULL) {
    set_has_value_name();
  } else {
    clear_has_value_name();
  }
  value_name_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value_name);
  // @@protoc_insertion_point(field_set_allocated:pmidgserialized.ComponentValueFloat.value_name)
}

// required float value = 2;
inline bool ComponentValueFloat::has_value() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void ComponentValueFloat::set_has_value() {
  _has_bits_[0] |= 0x00000002u;
}
inline void ComponentValueFloat::clear_has_value() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void ComponentValueFloat::clear_value() {
  value_ = 0;
  clear_has_value();
}
inline float ComponentValueFloat::value() const {
  // @@protoc_insertion_point(field_get:pmidgserialized.ComponentValueFloat.value)
  return value_;
}
inline void ComponentValueFloat::set_value(float value) {
  set_has_value();
  value_ = value;
  // @@protoc_insertion_point(field_set:pmidgserialized.ComponentValueFloat.value)
}

#endif  // !PROTOBUF_INLINE_NOT_IN_HEADERS
// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------


// @@protoc_insertion_point(namespace_scope)


}  // namespace pmidgserialized

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_gamestate_2eproto__INCLUDED
